FROM prestashop/base:$container_version
LABEL maintainer="PrestaShop Core Team <coreteam@prestashop.com>"

RUN apt update
RUN apt -y install git

ENV PS_BRANCH=$branch_version
ENV NODE_VERSION=$node_version

CMD ["/tmp/docker_branch_run.sh"]
